#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

start_service() {

    procd_open_instance capture

    procd_set_param command \
        /usr/bin/dns-stream-capture

    procd_set_param respawn \
        3600 5 5

    procd_set_param stdout 1
    procd_set_param stderr 1

    procd_close_instance


    procd_open_instance processor

    procd_set_param command \
        /usr/bin/dns-stream-processor-loop

    procd_set_param respawn \
        3600 5 5

    procd_set_param stdout 1
    procd_set_param stderr 1

    procd_close_instance
}
